name: ${PROJECT}

volumes:
  node_modules:

networks:
  proxy:

services:
  nginx:
    image: nginx:1.28-alpine
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      proxy:
        aliases:
          - ${CNAME}

  php:
    image: php:8.4-fpm-bookworm
    volumes:
      - ./public:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./php-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      APP_ENV: development
    networks:
      - proxy

  vite:
    image: node:22.16-slim
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/vite/node_modules
    command: npm run --prefix vite dev -- --host 0.0.0.0
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
    networks:
      - proxy
    profiles:
      - vite
